name: Sync SLL.io to Gowreesh-VT.github.io/SLL

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight

jobs:
  sync_sll:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Gowreesh-VT.github.io
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Clone SLL.io repository
        run: |
          git clone --depth=1 https://github.com/Gowreesh-VT/SLL.io.git temp-sll
          rsync -av --delete temp-sll/ SLL/
          rm -rf temp-sll
          git add SLL/
          git commit -m "Synced SLL.io to SLL folder" || echo "No changes to commit"

      - name: Push changes to Gowreesh-VT.github.io
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Gowreesh-VT/Gowreesh-VT.github.io.git main
